### ISSUE TITLE
 the first argument must be callable

### ISSUE THREAD

**Issue by FulufheloM** [basiclab/CPCStoryVisualization-Pytorch#1]
Hi 
Please assist getting the below error when running the main_pororo.py
  File "main_pororo.py", line 87, in <module>
    video_transforms = functools.partial(video_transform, image_transform=image_transforms) # Only need to feed video later
TypeError: the first argument must be callable

**Comment by theblackcat102** [comment]
Hi you need to include a configuration file name. For example:

```
python main_pororo.py --cfg ./consistency.yml
```

note, you need to change the DATA_DIR into your datasets path

**Comment by sws503** [comment]
```
Traceback (most recent call last):
  File "main_pororo.py", line 87, in <module>
    video_transforms = functools.partial(video_transform, image_transform=image_transforms) # Only need to feed video later
TypeError: the first argument must be callable
```

I checked DATA_DIR and config files.
But I got the same error and I can't solve the problem by using your advice.
Is there anything I have to check it?

**Comment by theblackcat102** [comment]
@sws503  if you remove the comment of [line 18](https://github.com/basiclab/CPCStoryVisualization-Pytorch/blob/e34ecf12c3d8de6e17098243c843ebd608820783/main_pororo.py#L18) , does this solve your problem?

**Comment by sws503** [comment]
Thanks. It solved
