### ISSUE TITLE
Preprocessing on the Pororo dataset

### ISSUE THREAD

**Issue by awkrail** [basiclab/CPCStoryVisualization-Pytorch#3]
Hi, I am very interested in your paper and the task to generate a story from an image sequence.
I have some questions about the `preprocess_pororo.py`.

1. The code does not preprocess
I found the code process nothing except for printing file names in the Pororo dataset.
```python
if __name__ == "__main__":
	import os, glob, PIL
	for filename in glob.glob('/mnt/storage/pororoSV/Scenes_Dialogues/*/*/*.gif'):
		img_name = os.path.basename(filename)
		print(img_name)
```
How do I modify the code to preprocess the dataset?

2. How can I get `pororo_png/descriptions_vec.npy` file?
At L62 on `preprocess_pororo.py`, numpy file is loaded as:
```python
descriptions_vec = np.load("pororo_png/descriptions_vec.npy", encoding='bytes').item()
```
But, I have no idea how to get this file. Could you clarify it (any documents)?

**Comment by theblackcat102** [comment]
Hi @misogil0116 I'm sorry for the late reply. The description_vec.npy can be found at the download links : [google drive](https://drive.google.com/file/d/1rDjmMr3iqkBjEoE6g05iGyY1I7pi8FTn/view?usp=sharing)

once you unzip the file, you can find the required image and preprocessed vector cache inside

**Comment by awkrail** [comment]
Thank you!
